export const prefectures = [
  { value: '', label: '選択してください' },
  { value: '北海道', label: '北海道' },
  { value: '青森県', label: '青森県' },
  { value: '岩手県', label: '岩手県' },
  { value: '宮城県', label: '宮城県' },
  { value: '秋田県', label: '秋田県' },
  { value: '山形県', label: '山形県' },
  { value: '福島県', label: '福島県' },
  { value: '茨城県', label: '茨城県' },
  { value: '栃木県', label: '栃木県' },
  { value: '群馬県', label: '群馬県' },
  { value: '埼玉県', label: '埼玉県' },
  { value: '千葉県', label: '千葉県' },
  { value: '東京都', label: '東京都' },
  { value: '神奈川県', label: '神奈川県' },
  { value: '新潟県', label: '新潟県' },
  { value: '富山県', label: '富山県' },
  { value: '石川県', label: '石川県' },
  { value: '福井県', label: '福井県' },
  { value: '山梨県', label: '山梨県' },
  { value: '長野県', label: '長野県' },
  { value: '岐阜県', label: '岐阜県' },
  { value: '静岡県', label: '静岡県' },
  { value: '愛知県', label: '愛知県' },
  { value: '三重県', label: '三重県' },
  { value: '滋賀県', label: '滋賀県' },
  { value: '京都府', label: '京都府' },
  { value: '大阪府', label: '大阪府' },
  { value: '兵庫県', label: '兵庫県' },
  { value: '奈良県', label: '奈良県' },
  { value: '和歌山県', label: '和歌山県' },
  { value: '鳥取県', label: '鳥取県' },
  { value: '島根県', label: '島根県' },
  { value: '岡山県', label: '岡山県' },
  { value: '広島県', label: '広島県' },
  { value: '山口県', label: '山口県' },
  { value: '徳島県', label: '徳島県' },
  { value: '香川県', label: '香川県' },
  { value: '愛媛県', label: '愛媛県' },
  { value: '高知県', label: '高知県' },
  { value: '福岡県', label: '福岡県' },
  { value: '佐賀県', label: '佐賀県' },
  { value: '長崎県', label: '長崎県' },
  { value: '熊本県', label: '熊本県' },
  { value: '大分県', label: '大分県' },
  { value: '宮崎県', label: '宮崎県' },
  { value: '鹿児島県', label: '鹿児島県' },
  { value: '沖縄県', label: '沖縄県' }
]

export const municipalities = {
  '北海道': [
    { value: '', label: '選択してください' },
    { value: '札幌市', label: '札幌市' },
    { value: '旭川市', label: '旭川市' },
    { value: '函館市', label: '函館市' },
    { value: '小樽市', label: '小樽市' },
    { value: '室蘭市', label: '室蘭市' }
  ],
  '東京都': [
    { value: '', label: '選択してください' },
    { value: '千代田区', label: '千代田区' },
    { value: '中央区', label: '中央区' },
    { value: '港区', label: '港区' },
    { value: '新宿区', label: '新宿区' },
    { value: '文京区', label: '文京区' },
    { value: '台東区', label: '台東区' },
    { value: '墨田区', label: '墨田区' },
    { value: '江東区', label: '江東区' },
    { value: '品川区', label: '品川区' },
    { value: '目黒区', label: '目黒区' },
    { value: '大田区', label: '大田区' },
    { value: '世田谷区', label: '世田谷区' },
    { value: '渋谷区', label: '渋谷区' },
    { value: '中野区', label: '中野区' },
    { value: '杉並区', label: '杉並区' },
    { value: '豊島区', label: '豊島区' },
    { value: '北区', label: '北区' },
    { value: '荒川区', label: '荒川区' },
    { value: '板橋区', label: '板橋区' },
    { value: '練馬区', label: '練馬区' },
    { value: '足立区', label: '足立区' },
    { value: '葛飾区', label: '葛飾区' },
    { value: '江戸川区', label: '江戸川区' }
  ],
  '神奈川県': [
    { value: '', label: '選択してください' },
    { value: '横浜市', label: '横浜市' },
    { value: '川崎市', label: '川崎市' },
    { value: '相模原市', label: '相模原市' },
    { value: '横須賀市', label: '横須賀市' },
    { value: '藤沢市', label: '藤沢市' },
    { value: '茅ヶ崎市', label: '茅ヶ崎市' },
    { value: '逗子市', label: '逗子市' },
    { value: '三浦市', label: '三浦市' },
    { value: '厚木市', label: '厚木市' },
    { value: '大和市', label: '大和市' },
    { value: '海老名市', label: '海老名市' },
    { value: '座間市', label: '座間市' },
    { value: '綾瀬市', label: '綾瀬市' }
  ],
  '大阪府': [
    { value: '', label: '選択してください' },
    { value: '大阪市', label: '大阪市' },
    { value: '堺市', label: '堺市' },
    { value: '豊中市', label: '豊中市' },
    { value: '池田市', label: '池田市' },
    { value: '吹田市', label: '吹田市' },
    { value: '泉大津市', label: '泉大津市' },
    { value: '高槻市', label: '高槻市' },
    { value: '茨木市', label: '茨木市' },
    { value: '八尾市', label: '八尾市' },
    { value: '泉佐野市', label: '泉佐野市' },
    { value: '富田林市', label: '富田林市' },
    { value: '寝屋川市', label: '寝屋川市' },
    { value: '河内長野市', label: '河内長野市' },
    { value: '松原市', label: '松原市' },
    { value: '大東市', label: '大東市' },
    { value: '和泉市', label: '和泉市' },
    { value: '箕面市', label: '箕面市' },
    { value: '柏原市', label: '柏原市' },
    { value: '羽曳野市', label: '羽曳野市' },
    { value: '門真市', label: '門真市' },
    { value: '摂津市', label: '摂津市' },
    { value: '高石市', label: '高石市' },
    { value: '藤井寺市', label: '藤井寺市' },
    { value: '東大阪市', label: '東大阪市' },
    { value: '泉南市', label: '泉南市' },
    { value: '四條畷市', label: '四條畷市' },
    { value: '交野市', label: '交野市' },
    { value: '大阪狭山市', label: '大阪狭山市' },
    { value: '阪南市', label: '阪南市' }
  ],
  '愛知県': [
    { value: '', label: '選択してください' },
    { value: '名古屋市', label: '名古屋市' },
    { value: '豊橋市', label: '豊橋市' },
    { value: '岡崎市', label: '岡崎市' },
    { value: '一宮市', label: '一宮市' },
    { value: '瀬戸市', label: '瀬戸市' },
    { value: '半田市', label: '半田市' },
    { value: '春日井市', label: '春日井市' },
    { value: '豊川市', label: '豊川市' },
    { value: '津島市', label: '津島市' },
    { value: '碧南市', label: '碧南市' },
    { value: '刈谷市', label: '刈谷市' },
    { value: '豊田市', label: '豊田市' },
    { value: '安城市', label: '安城市' },
    { value: '西尾市', label: '西尾市' },
    { value: '蒲郡市', label: '蒲郡市' },
    { value: '犬山市', label: '犬山市' },
    { value: '常滑市', label: '常滑市' },
    { value: '江南市', label: '江南市' },
    { value: '小牧市', label: '小牧市' },
    { value: '稲沢市', label: '稲沢市' },
    { value: '新城市', label: '新城市' },
    { value: '知多市', label: '知多市' },
    { value: '知立市', label: '知立市' },
    { value: '尾張旭市', label: '尾張旭市' },
    { value: '高浜市', label: '高浜市' },
    { value: '岩倉市', label: '岩倉市' },
    { value: '豊明市', label: '豊明市' },
    { value: '日進市', label: '日進市' },
    { value: '田原市', label: '田原市' },
    { value: '愛西市', label: '愛西市' },
    { value: '清須市', label: '清須市' },
    { value: '北名古屋市', label: '北名古屋市' },
    { value: '弥富市', label: '弥富市' },
    { value: 'みよし市', label: 'みよし市' },
    { value: 'あま市', label: 'あま市' },
    { value: '長久手市', label: '長久手市' }
  ]
}

// デフォルトの市町村リスト（都道府県が選択されていない場合）
export const defaultMunicipalities = [
  { value: '', label: '都道府県を先に選択してください' }
]