export const prefectures = [
  { value: '', label: '選択してください' },
  { value: '北海道', label: '北海道' },
  { value: '青森県', label: '青森県' },
  { value: '岩手県', label: '岩手県' },
  { value: '宮城県', label: '宮城県' },
  { value: '秋田県', label: '秋田県' },
  { value: '山形県', label: '山形県' },
  { value: '福島県', label: '福島県' },
  { value: '茨城県', label: '茨城県' },
  { value: '栃木県', label: '栃木県' },
  { value: '群馬県', label: '群馬県' },
  { value: '埼玉県', label: '埼玉県' },
  { value: '千葉県', label: '千葉県' },
  { value: '東京都', label: '東京都' },
  { value: '神奈川県', label: '神奈川県' },
  { value: '新潟県', label: '新潟県' },
  { value: '富山県', label: '富山県' },
  { value: '石川県', label: '石川県' },
  { value: '福井県', label: '福井県' },
  { value: '山梨県', label: '山梨県' },
  { value: '長野県', label: '長野県' },
  { value: '岐阜県', label: '岐阜県' },
  { value: '静岡県', label: '静岡県' },
  { value: '愛知県', label: '愛知県' },
  { value: '三重県', label: '三重県' },
  { value: '滋賀県', label: '滋賀県' },
  { value: '京都府', label: '京都府' },
  { value: '大阪府', label: '大阪府' },
  { value: '兵庫県', label: '兵庫県' },
  { value: '奈良県', label: '奈良県' },
  { value: '和歌山県', label: '和歌山県' },
  { value: '鳥取県', label: '鳥取県' },
  { value: '島根県', label: '島根県' },
  { value: '岡山県', label: '岡山県' },
  { value: '広島県', label: '広島県' },
  { value: '山口県', label: '山口県' },
  { value: '徳島県', label: '徳島県' },
  { value: '香川県', label: '香川県' },
  { value: '愛媛県', label: '愛媛県' },
  { value: '高知県', label: '高知県' },
  { value: '福岡県', label: '福岡県' },
  { value: '佐賀県', label: '佐賀県' },
  { value: '長崎県', label: '長崎県' },
  { value: '熊本県', label: '熊本県' },
  { value: '大分県', label: '大分県' },
  { value: '宮崎県', label: '宮崎県' },
  { value: '鹿児島県', label: '鹿児島県' },
  { value: '沖縄県', label: '沖縄県' }
]

// 都道府県別の市町村データ（配列形式に統一）
export const municipalities = [
  {
    prefecture: '北海道',
    cities: [
      { value: '', label: '選択してください' },
      { value: '札幌市', label: '札幌市' },
      { value: '旭川市', label: '旭川市' },
      { value: '函館市', label: '函館市' },
      { value: '小樽市', label: '小樽市' },
      { value: '室蘭市', label: '室蘭市' }
    ]
  },
  {
    prefecture: '茨城県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '水戸市', label: '水戸市' },
      { value: '日立市', label: '日立市' },
      { value: '土浦市', label: '土浦市' },
      { value: '古河市', label: '古河市' },
      { value: '石岡市', label: '石岡市' },
      { value: '結城市', label: '結城市' },
      { value: '龍ケ崎市', label: '龍ケ崎市' },
      { value: '下妻市', label: '下妻市' },
      { value: '常総市', label: '常総市' },
      { value: '常陸太田市', label: '常陸太田市' },
      { value: '高萩市', label: '高萩市' },
      { value: '北茨城市', label: '北茨城市' },
      { value: '笠間市', label: '笠間市' },
      { value: '取手市', label: '取手市' },
      { value: '牛久市', label: '牛久市' },
      { value: 'つくば市', label: 'つくば市' },
      { value: 'ひたちなか市', label: 'ひたちなか市' },
      { value: '鹿嶋市', label: '鹿嶋市' },
      { value: '潮来市', label: '潮来市' },
      { value: '守谷市', label: '守谷市' },
      { value: '常陸大宮市', label: '常陸大宮市' },
      { value: '那珂市', label: '那珂市' },
      { value: '筑西市', label: '筑西市' },
      { value: '坂東市', label: '坂東市' },
      { value: '稲敷市', label: '稲敷市' },
      { value: 'かすみがうら市', label: 'かすみがうら市' },
      { value: '桜川市', label: '桜川市' },
      { value: '神栖市', label: '神栖市' },
      { value: '行方市', label: '行方市' },
      { value: '鉾田市', label: '鉾田市' },
      { value: 'つくばみらい市', label: 'つくばみらい市' },
      { value: '小美玉市', label: '小美玉市' }
    ]
  },
  {
    prefecture: '栃木県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '宇都宮市', label: '宇都宮市' },
      { value: '足利市', label: '足利市' },
      { value: '栃木市', label: '栃木市' },
      { value: '佐野市', label: '佐野市' },
      { value: '鹿沼市', label: '鹿沼市' },
      { value: '日光市', label: '日光市' },
      { value: '小山市', label: '小山市' },
      { value: '真岡市', label: '真岡市' },
      { value: '大田原市', label: '大田原市' },
      { value: '矢板市', label: '矢板市' },
      { value: '那須塩原市', label: '那須塩原市' },
      { value: 'さくら市', label: 'さくら市' },
      { value: '那須烏山市', label: '那須烏山市' },
      { value: '下野市', label: '下野市' }
    ]
  },
  {
    prefecture: '群馬県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '前橋市', label: '前橋市' },
      { value: '高崎市', label: '高崎市' },
      { value: '桐生市', label: '桐生市' },
      { value: '伊勢崎市', label: '伊勢崎市' },
      { value: '太田市', label: '太田市' },
      { value: '沼田市', label: '沼田市' },
      { value: '館林市', label: '館林市' },
      { value: '渋川市', label: '渋川市' },
      { value: '藤岡市', label: '藤岡市' },
      { value: '富岡市', label: '富岡市' },
      { value: '安中市', label: '安中市' },
      { value: 'みどり市', label: 'みどり市' },
      { value: '榛東村', label: '榛東村' },
      { value: '吉岡町', label: '吉岡町' },
      { value: '上野村', label: '上野村' },
      { value: '神流町', label: '神流町' },
      { value: '下仁田町', label: '下仁田町' },
      { value: '南牧村', label: '南牧村' },
      { value: '甘楽町', label: '甘楽町' },
      { value: '中之条町', label: '中之条町' },
      { value: '長野原町', label: '長野原町' },
      { value: '嬬恋村', label: '嬬恋村' },
      { value: '草津町', label: '草津町' },
      { value: '六合村', label: '六合村' },
      { value: '東吾妻町', label: '東吾妻町' },
      { value: '片品村', label: '片品村' },
      { value: '川場村', label: '川場村' },
      { value: '昭和村', label: '昭和村' },
      { value: 'みなかみ町', label: 'みなかみ町' },
      { value: '玉村町', label: '玉村町' },
      { value: '板倉町', label: '板倉町' },
      { value: '明和町', label: '明和町' },
      { value: '千代田町', label: '千代田町' },
      { value: '大泉町', label: '大泉町' },
      { value: '邑楽町', label: '邑楽町' }
    ]
  },
  {
    prefecture: '埼玉県',
    cities: [
      { value: '', label: '選択してください' },
      { value: 'さいたま市', label: 'さいたま市' },
      { value: '川越市', label: '川越市' },
      { value: '熊谷市', label: '熊谷市' },
      { value: '川口市', label: '川口市' },
      { value: '行田市', label: '行田市' },
      { value: '秩父市', label: '秩父市' },
      { value: '所沢市', label: '所沢市' },
      { value: '飯能市', label: '飯能市' },
      { value: '加須市', label: '加須市' },
      { value: '本庄市', label: '本庄市' },
      { value: '東松山市', label: '東松山市' },
      { value: '春日部市', label: '春日部市' },
      { value: '狭山市', label: '狭山市' },
      { value: '羽生市', label: '羽生市' },
      { value: '鴻巣市', label: '鴻巣市' },
      { value: '深谷市', label: '深谷市' },
      { value: '上尾市', label: '上尾市' },
      { value: '草加市', label: '草加市' },
      { value: '越谷市', label: '越谷市' },
      { value: '蕨市', label: '蕨市' },
      { value: '戸田市', label: '戸田市' },
      { value: '入間市', label: '入間市' },
      { value: '朝霞市', label: '朝霞市' },
      { value: '志木市', label: '志木市' },
      { value: '和光市', label: '和光市' },
      { value: '新座市', label: '新座市' },
      { value: '桶川市', label: '桶川市' },
      { value: '久喜市', label: '久喜市' },
      { value: '北本市', label: '北本市' },
      { value: '八潮市', label: '八潮市' },
      { value: '富士見市', label: '富士見市' },
      { value: '三郷市', label: '三郷市' },
      { value: '蓮田市', label: '蓮田市' },
      { value: '坂戸市', label: '坂戸市' },
      { value: '幸手市', label: '幸手市' },
      { value: '鶴ヶ島市', label: '鶴ヶ島市' },
      { value: '日高市', label: '日高市' },
      { value: '吉川市', label: '吉川市' },
      { value: 'ふじみ野市', label: 'ふじみ野市' },
      { value: '白岡市', label: '白岡市' }
    ]
  },
  {
    prefecture: '千葉県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '千葉市', label: '千葉市' },
      { value: '銚子市', label: '銚子市' },
      { value: '市川市', label: '市川市' },
      { value: '船橋市', label: '船橋市' },
      { value: '館山市', label: '館山市' },
      { value: '木更津市', label: '木更津市' },
      { value: '松戸市', label: '松戸市' },
      { value: '野田市', label: '野田市' },
      { value: '茂原市', label: '茂原市' },
      { value: '成田市', label: '成田市' },
      { value: '佐倉市', label: '佐倉市' },
      { value: '東金市', label: '東金市' },
      { value: '旭市', label: '旭市' },
      { value: '習志野市', label: '習志野市' },
      { value: '柏市', label: '柏市' },
      { value: '勝浦市', label: '勝浦市' },
      { value: '市原市', label: '市原市' },
      { value: '流山市', label: '流山市' },
      { value: '八千代市', label: '八千代市' },
      { value: '我孫子市', label: '我孫子市' },
      { value: '鴨川市', label: '鴨川市' },
      { value: '鎌ケ谷市', label: '鎌ケ谷市' },
      { value: '君津市', label: '君津市' },
      { value: '富津市', label: '富津市' },
      { value: '浦安市', label: '浦安市' },
      { value: '四街道市', label: '四街道市' },
      { value: '袖ケ浦市', label: '袖ケ浦市' },
      { value: '八街市', label: '八街市' },
      { value: '印西市', label: '印西市' },
      { value: '白井市', label: '白井市' },
      { value: '富里市', label: '富里市' },
      { value: '南房総市', label: '南房総市' },
      { value: '匝瑳市', label: '匝瑳市' },
      { value: '香取市', label: '香取市' },
      { value: '山武市', label: '山武市' },
      { value: 'いすみ市', label: 'いすみ市' },
      { value: '大網白里市', label: '大網白里市' },
      { value: '酒々井町', label: '酒々井町' },
      { value: '栄町', label: '栄町' },
      { value: '神崎町', label: '神崎町' },
      { value: '多古町', label: '多古町' },
      { value: '東庄町', label: '東庄町' },
      { value: '九十九里町', label: '九十九里町' },
      { value: '芝山町', label: '芝山町' },
      { value: '横芝光町', label: '横芝光町' },
      { value: '一宮町', label: '一宮町' },
      { value: '睦沢町', label: '睦沢町' },
      { value: '長生村', label: '長生村' },
      { value: '白子町', label: '白子町' },
      { value: '長柄町', label: '長柄町' },
      { value: '長南町', label: '長南町' },
      { value: '大多喜町', label: '大多喜町' },
      { value: '御宿町', label: '御宿町' },
      { value: '鋸南町', label: '鋸南町' }
    ]
  },
  {
    prefecture: '東京都',
    cities: [
      { value: '', label: '選択してください' },
      { value: '千代田区', label: '千代田区' },
      { value: '中央区', label: '中央区' },
      { value: '港区', label: '港区' },
      { value: '新宿区', label: '新宿区' },
      { value: '文京区', label: '文京区' },
      { value: '台東区', label: '台東区' },
      { value: '墨田区', label: '墨田区' },
      { value: '江東区', label: '江東区' },
      { value: '品川区', label: '品川区' },
      { value: '目黒区', label: '目黒区' },
      { value: '大田区', label: '大田区' },
      { value: '世田谷区', label: '世田谷区' },
      { value: '渋谷区', label: '渋谷区' },
      { value: '中野区', label: '中野区' },
      { value: '杉並区', label: '杉並区' },
      { value: '豊島区', label: '豊島区' },
      { value: '北区', label: '北区' },
      { value: '荒川区', label: '荒川区' },
      { value: '板橋区', label: '板橋区' },
      { value: '練馬区', label: '練馬区' },
      { value: '足立区', label: '足立区' },
      { value: '葛飾区', label: '葛飾区' },
      { value: '江戸川区', label: '江戸川区' },
      { value: '八王子市', label: '八王子市' },
      { value: '立川市', label: '立川市' },
      { value: '武蔵野市', label: '武蔵野市' },
      { value: '三鷹市', label: '三鷹市' },
      { value: '青梅市', label: '青梅市' },
      { value: '府中市', label: '府中市' },
      { value: '昭島市', label: '昭島市' },
      { value: '調布市', label: '調布市' },
      { value: '町田市', label: '町田市' },
      { value: '小金井市', label: '小金井市' },
      { value: '小平市', label: '小平市' },
      { value: '日野市', label: '日野市' },
      { value: '東村山市', label: '東村山市' },
      { value: '国分寺市', label: '国分寺市' },
      { value: '国立市', label: '国立市' },
      { value: '福生市', label: '福生市' },
      { value: '狛江市', label: '狛江市' },
      { value: '東大和市', label: '東大和市' },
      { value: '清瀬市', label: '清瀬市' },
      { value: '東久留米市', label: '東久留米市' },
      { value: '武蔵村山市', label: '武蔵村山市' },
      { value: '多摩市', label: '多摩市' },
      { value: '稲城市', label: '稲城市' },
      { value: '羽村市', label: '羽村市' },
      { value: 'あきる野市', label: 'あきる野市' },
      { value: '西東京市', label: '西東京市' },
      { value: '瑞穂町', label: '瑞穂町' },
      { value: '日の出町', label: '日の出町' },
      { value: '檜原村', label: '檜原村' },
      { value: '奥多摩町', label: '奥多摩町' },
      { value: '大島町', label: '大島町' },
      { value: '利島村', label: '利島村' },
      { value: '新島村', label: '新島村' },
      { value: '神津島村', label: '神津島村' },
      { value: '三宅村', label: '三宅村' },
      { value: '御蔵島村', label: '御蔵島村' },
      { value: '八丈町', label: '八丈町' },
      { value: '青ヶ島村', label: '青ヶ島村' },
      { value: '小笠原村', label: '小笠原村' }
    ]
  },
  {
    prefecture: '神奈川県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '横浜市', label: '横浜市' },
      { value: '川崎市', label: '川崎市' },
      { value: '相模原市', label: '相模原市' },
      { value: '横須賀市', label: '横須賀市' },
      { value: '藤沢市', label: '藤沢市' },
      { value: '茅ヶ崎市', label: '茅ヶ崎市' },
      { value: '逗子市', label: '逗子市' },
      { value: '三浦市', label: '三浦市' },
      { value: '厚木市', label: '厚木市' },
      { value: '大和市', label: '大和市' },
      { value: '海老名市', label: '海老名市' },
      { value: '座間市', label: '座間市' },
      { value: '綾瀬市', label: '綾瀬市' },
      { value: '小田原市', label: '小田原市' },
      { value: '平塚市', label: '平塚市' },
      { value: '鎌倉市', label: '鎌倉市' },
      { value: '秦野市', label: '秦野市' },
      { value: '伊勢原市', label: '伊勢原市' },
      { value: '南足柄市', label: '南足柄市' },
      { value: '開成町', label: '開成町' },
      { value: '箱根町', label: '箱根町' },
      { value: '真鶴町', label: '真鶴町' },
      { value: '湯河原町', label: '湯河原町' },
      { value: '愛川町', label: '愛川町' },
      { value: '清川村', label: '清川村' },
      { value: '中井町', label: '中井町' },
      { value: '大磯町', label: '大磯町' },
      { value: '二宮町', label: '二宮町' },
      { value: '松田町', label: '松田町' },
      { value: '山北町', label: '山北町' }
    ]
  },
  {
    prefecture: '大阪府',
    cities: [
      { value: '', label: '選択してください' },
      { value: '大阪市', label: '大阪市' },
      { value: '堺市', label: '堺市' },
      { value: '豊中市', label: '豊中市' },
      { value: '池田市', label: '池田市' },
      { value: '吹田市', label: '吹田市' },
      { value: '泉大津市', label: '泉大津市' },
      { value: '高槻市', label: '高槻市' },
      { value: '茨木市', label: '茨木市' },
      { value: '八尾市', label: '八尾市' },
      { value: '泉佐野市', label: '泉佐野市' },
      { value: '富田林市', label: '富田林市' },
      { value: '寝屋川市', label: '寝屋川市' },
      { value: '河内長野市', label: '河内長野市' },
      { value: '松原市', label: '松原市' },
      { value: '大東市', label: '大東市' },
      { value: '和泉市', label: '和泉市' },
      { value: '箕面市', label: '箕面市' },
      { value: '柏原市', label: '柏原市' },
      { value: '羽曳野市', label: '羽曳野市' },
      { value: '門真市', label: '門真市' },
      { value: '摂津市', label: '摂津市' },
      { value: '高石市', label: '高石市' },
      { value: '藤井寺市', label: '藤井寺市' },
      { value: '東大阪市', label: '東大阪市' },
      { value: '泉南市', label: '泉南市' },
      { value: '四條畷市', label: '四條畷市' },
      { value: '交野市', label: '交野市' },
      { value: '大阪狭山市', label: '大阪狭山市' },
      { value: '阪南市', label: '阪南市' }
    ]
  },
  {
    prefecture: '愛知県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '名古屋市', label: '名古屋市' },
      { value: '豊橋市', label: '豊橋市' },
      { value: '岡崎市', label: '岡崎市' },
      { value: '一宮市', label: '一宮市' },
      { value: '瀬戸市', label: '瀬戸市' },
      { value: '半田市', label: '半田市' },
      { value: '春日井市', label: '春日井市' },
      { value: '豊川市', label: '豊川市' },
      { value: '津島市', label: '津島市' },
      { value: '碧南市', label: '碧南市' },
      { value: '刈谷市', label: '刈谷市' },
      { value: '豊田市', label: '豊田市' },
      { value: '安城市', label: '安城市' },
      { value: '西尾市', label: '西尾市' },
      { value: '蒲郡市', label: '蒲郡市' },
      { value: '犬山市', label: '犬山市' },
      { value: '常滑市', label: '常滑市' },
      { value: '江南市', label: '江南市' },
      { value: '小牧市', label: '小牧市' },
      { value: '稲沢市', label: '稲沢市' },
      { value: '新城市', label: '新城市' },
      { value: '知多市', label: '知多市' },
      { value: '知立市', label: '知立市' },
      { value: '尾張旭市', label: '尾張旭市' },
      { value: '高浜市', label: '高浜市' },
      { value: '岩倉市', label: '岩倉市' },
      { value: '豊明市', label: '豊明市' },
      { value: '日進市', label: '日進市' },
      { value: '田原市', label: '田原市' },
      { value: '愛西市', label: '愛西市' },
      { value: '清須市', label: '清須市' },
      { value: '北名古屋市', label: '北名古屋市' },
      { value: '弥富市', label: '弥富市' },
      { value: 'みよし市', label: 'みよし市' },
      { value: 'あま市', label: 'あま市' },
      { value: '長久手市', label: '長久手市' }
    ]
  },
  {
    prefecture: '福岡県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '福岡市', label: '福岡市' },
      { value: '北九州市', label: '北九州市' },
      { value: '久留米市', label: '久留米市' },
      { value: '大牟田市', label: '大牟田市' },
      { value: '直方市', label: '直方市' },
      { value: '飯塚市', label: '飯塚市' },
      { value: '田川市', label: '田川市' },
      { value: '柳川市', label: '柳川市' },
      { value: '八女市', label: '八女市' },
      { value: '筑後市', label: '筑後市' },
      { value: '大川市', label: '大川市' },
      { value: '行橋市', label: '行橋市' },
      { value: '豊前市', label: '豊前市' },
      { value: '中間市', label: '中間市' },
      { value: '小郡市', label: '小郡市' },
      { value: '筑紫野市', label: '筑紫野市' },
      { value: '春日市', label: '春日市' },
      { value: '大野城市', label: '大野城市' },
      { value: '宗像市', label: '宗像市' },
      { value: '太宰府市', label: '太宰府市' },
      { value: '古賀市', label: '古賀市' },
      { value: '福津市', label: '福津市' },
      { value: 'うきは市', label: 'うきは市' },
      { value: '宮若市', label: '宮若市' },
      { value: '嘉麻市', label: '嘉麻市' },
      { value: '朝倉市', label: '朝倉市' },
      { value: 'みやま市', label: 'みやま市' },
      { value: '糸島市', label: '糸島市' },
      { value: '那珂川市', label: '那珂川市' }
    ]
  },
  {
    prefecture: '京都府',
    cities: [
      { value: '', label: '選択してください' },
      { value: '京都市', label: '京都市' },
      { value: '福知山市', label: '福知山市' },
      { value: '舞鶴市', label: '舞鶴市' },
      { value: '綾部市', label: '綾部市' },
      { value: '宇治市', label: '宇治市' },
      { value: '宮津市', label: '宮津市' },
      { value: '亀岡市', label: '亀岡市' },
      { value: '城陽市', label: '城陽市' },
      { value: '向日市', label: '向日市' },
      { value: '長岡京市', label: '長岡京市' },
      { value: '八幡市', label: '八幡市' },
      { value: '京田辺市', label: '京田辺市' },
      { value: '京丹後市', label: '京丹後市' },
      { value: '南丹市', label: '南丹市' },
      { value: '木津川市', label: '木津川市' },
      { value: '乙訓郡', label: '乙訓郡' },
      { value: '久世郡', label: '久世郡' },
      { value: '綴喜郡', label: '綴喜郡' },
      { value: '相楽郡', label: '相楽郡' },
      { value: '船井郡', label: '船井郡' },
      { value: '与謝郡', label: '与謝郡' }
    ]
  },
  {
    prefecture: '兵庫県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '神戸市', label: '神戸市' },
      { value: '姫路市', label: '姫路市' },
      { value: '尼崎市', label: '尼崎市' },
      { value: '明石市', label: '明石市' },
      { value: '西宮市', label: '西宮市' },
      { value: '洲本市', label: '洲本市' },
      { value: '芦屋市', label: '芦屋市' },
      { value: '伊丹市', label: '伊丹市' },
      { value: '相生市', label: '相生市' },
      { value: '豊岡市', label: '豊岡市' },
      { value: '加古川市', label: '加古川市' },
      { value: '赤穂市', label: '赤穂市' },
      { value: '西脇市', label: '西脇市' },
      { value: '宝塚市', label: '宝塚市' },
      { value: '三木市', label: '三木市' },
      { value: '高砂市', label: '高砂市' },
      { value: '川西市', label: '川西市' },
      { value: '小野市', label: '小野市' },
      { value: '三田市', label: '三田市' },
      { value: '加西市', label: '加西市' },
      { value: '丹波篠山市', label: '丹波篠山市' },
      { value: '養父市', label: '養父市' },
      { value: '丹波市', label: '丹波市' },
      { value: '南あわじ市', label: '南あわじ市' },
      { value: '朝来市', label: '朝来市' },
      { value: '淡路市', label: '淡路市' },
      { value: '宍粟市', label: '宍粟市' },
      { value: '加東市', label: '加東市' },
      { value: 'たつの市', label: 'たつの市' }
    ]
  },
  {
    prefecture: '静岡県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '静岡市', label: '静岡市' },
      { value: '浜松市', label: '浜松市' },
      { value: '沼津市', label: '沼津市' },
      { value: '熱海市', label: '熱海市' },
      { value: '三島市', label: '三島市' },
      { value: '富士宮市', label: '富士宮市' },
      { value: '伊東市', label: '伊東市' },
      { value: '島田市', label: '島田市' },
      { value: '富士市', label: '富士市' },
      { value: '磐田市', label: '磐田市' },
      { value: '焼津市', label: '焼津市' },
      { value: '掛川市', label: '掛川市' },
      { value: '藤枝市', label: '藤枝市' },
      { value: '御殿場市', label: '御殿場市' },
      { value: '袋井市', label: '袋井市' },
      { value: '下田市', label: '下田市' },
      { value: '裾野市', label: '裾野市' },
      { value: '湖西市', label: '湖西市' },
      { value: '伊豆市', label: '伊豆市' },
      { value: '御前崎市', label: '御前崎市' },
      { value: '菊川市', label: '菊川市' },
      { value: '伊豆の国市', label: '伊豆の国市' },
      { value: '牧之原市', label: '牧之原市' }
    ]
  },
  {
    prefecture: '宮城県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '仙台市', label: '仙台市' },
      { value: '石巻市', label: '石巻市' },
      { value: '塩竈市', label: '塩竈市' },
      { value: '気仙沼市', label: '気仙沼市' },
      { value: '白石市', label: '白石市' },
      { value: '名取市', label: '名取市' },
      { value: '角田市', label: '角田市' },
      { value: '多賀城市', label: '多賀城市' },
      { value: '岩沼市', label: '岩沼市' },
      { value: '登米市', label: '登米市' },
      { value: '栗原市', label: '栗原市' },
      { value: '東松島市', label: '東松島市' },
      { value: '大崎市', label: '大崎市' },
      { value: '富谷市', label: '富谷市' }
    ]
  },
  {
    prefecture: '新潟県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '新潟市', label: '新潟市' },
      { value: '長岡市', label: '長岡市' },
      { value: '三条市', label: '三条市' },
      { value: '柏崎市', label: '柏崎市' },
      { value: '新発田市', label: '新発田市' },
      { value: '小千谷市', label: '小千谷市' },
      { value: '加茂市', label: '加茂市' },
      { value: '十日町市', label: '十日町市' },
      { value: '見附市', label: '見附市' },
      { value: '村上市', label: '村上市' },
      { value: '燕市', label: '燕市' },
      { value: '糸魚川市', label: '糸魚川市' },
      { value: '妙高市', label: '妙高市' },
      { value: '五泉市', label: '五泉市' },
      { value: '上越市', label: '上越市' },
      { value: '阿賀野市', label: '阿賀野市' },
      { value: '佐渡市', label: '佐渡市' },
      { value: '魚沼市', label: '魚沼市' },
      { value: '南魚沼市', label: '南魚沼市' },
      { value: '胎内市', label: '胎内市' }
    ]
  },
  {
    prefecture: '岩手県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '盛岡市', label: '盛岡市' },
      { value: '宮古市', label: '宮古市' },
      { value: '大船渡市', label: '大船渡市' },
      { value: '花巻市', label: '花巻市' },
      { value: '北上市', label: '北上市' },
      { value: '久慈市', label: '久慈市' },
      { value: '遠野市', label: '遠野市' },
      { value: '一関市', label: '一関市' },
      { value: '陸前高田市', label: '陸前高田市' },
      { value: '釜石市', label: '釜石市' },
      { value: '二戸市', label: '二戸市' },
      { value: '八幡平市', label: '八幡平市' },
      { value: '奥州市', label: '奥州市' },
      { value: '滝沢市', label: '滝沢市' },
      { value: '雫石町', label: '雫石町' },
      { value: '葛巻町', label: '葛巻町' },
      { value: '岩手町', label: '岩手町' },
      { value: '紫波町', label: '紫波町' },
      { value: '矢巾町', label: '矢巾町' },
      { value: '西和賀町', label: '西和賀町' },
      { value: '金ケ崎町', label: '金ケ崎町' },
      { value: '平泉町', label: '平泉町' },
      { value: '住田町', label: '住田町' },
      { value: '大槌町', label: '大槌町' },
      { value: '山田町', label: '山田町' },
      { value: '岩泉町', label: '岩泉町' },
      { value: '田野畑村', label: '田野畑村' },
      { value: '普代村', label: '普代村' },
      { value: '軽米町', label: '軽米町' },
      { value: '野田村', label: '野田村' },
      { value: '九戸村', label: '九戸村' },
      { value: '洋野町', label: '洋野町' },
      { value: '一戸町', label: '一戸町' }
    ]
  },
  {
    prefecture: '長野県',
    cities: [
      { value: '', label: '選択してください' },
      { value: '長野市', label: '長野市' },
      { value: '松本市', label: '松本市' },
      { value: '上田市', label: '上田市' },
      { value: '岡谷市', label: '岡谷市' },
      { value: '飯田市', label: '飯田市' },
      { value: '諏訪市', label: '諏訪市' },
      { value: '須坂市', label: '須坂市' },
      { value: '小諸市', label: '小諸市' },
      { value: '伊那市', label: '伊那市' },
      { value: '駒ヶ根市', label: '駒ヶ根市' },
      { value: '中野市', label: '中野市' },
      { value: '大町市', label: '大町市' },
      { value: '飯山市', label: '飯山市' },
      { value: '茅野市', label: '茅野市' },
      { value: '塩尻市', label: '塩尻市' },
      { value: '佐久市', label: '佐久市' },
      { value: '千曲市', label: '千曲市' },
      { value: '東御市', label: '東御市' },
      { value: '安曇野市', label: '安曇野市' },
      { value: '小海町', label: '小海町' },
      { value: '川上村', label: '川上村' },
      { value: '南牧村', label: '南牧村' },
      { value: '南相木村', label: '南相木村' },
      { value: '北相木村', label: '北相木村' },
      { value: '佐久穂町', label: '佐久穂町' },
      { value: '軽井沢町', label: '軽井沢町' },
      { value: '御代田町', label: '御代田町' },
      { value: '立科町', label: '立科町' },
      { value: '青木村', label: '青木村' },
      { value: '長和町', label: '長和町' },
      { value: '下諏訪町', label: '下諏訪町' },
      { value: '富士見町', label: '富士見町' },
      { value: '原村', label: '原村' },
      { value: '辰野町', label: '辰野町' },
      { value: '箕輪町', label: '箕輪町' },
      { value: '飯島町', label: '飯島町' },
      { value: '南箕輪村', label: '南箕輪村' },
      { value: '中川村', label: '中川村' },
      { value: '宮田村', label: '宮田村' },
      { value: '松川町', label: '松川町' },
      { value: '高森町', label: '高森町' },
      { value: '阿南町', label: '阿南町' },
      { value: '阿智村', label: '阿智村' },
      { value: '平谷村', label: '平谷村' },
      { value: '根羽村', label: '根羽村' },
      { value: '下條村', label: '下條村' },
      { value: '売木村', label: '売木村' },
      { value: '天龍村', label: '天龍村' },
      { value: '泰阜村', label: '泰阜村' },
      { value: '喬木村', label: '喬木村' },
      { value: '豊丘村', label: '豊丘村' },
      { value: '大鹿村', label: '大鹿村' },
      { value: '上松町', label: '上松町' },
      { value: '南木曽町', label: '南木曽町' },
      { value: '木祖村', label: '木祖村' },
      { value: '王滝村', label: '王滝村' },
      { value: '大桑村', label: '大桑村' },
      { value: '木曽町', label: '木曽町' },
      { value: '麻績村', label: '麻績村' },
      { value: '生坂村', label: '生坂村' },
      { value: '山形村', label: '山形村' },
      { value: '朝日村', label: '朝日村' },
      { value: '筑北村', label: '筑北村' },
      { value: '池田町', label: '池田町' },
      { value: '松川村', label: '松川村' },
      { value: '白馬村', label: '白馬村' },
      { value: '小谷村', label: '小谷村' },
      { value: '坂城町', label: '坂城町' },
      { value: '小布施町', label: '小布施町' },
      { value: '高山村', label: '高山村' },
      { value: '山ノ内町', label: '山ノ内町' },
      { value: '木島平村', label: '木島平村' },
      { value: '野沢温泉村', label: '野沢温泉村' },
      { value: '信濃町', label: '信濃町' },
      { value: '小川村', label: '小川村' },
      { value: '飯綱町', label: '飯綱町' },
      { value: '栄村', label: '栄村' }
    ]
  }
]

// デフォルトの市町村リスト（都道府県が選択されていない場合）
export const defaultMunicipalities = [
  { value: '', label: '都道府県を先に選択してください' }
]

// 都道府県名から市町村リストを取得するヘルパー関数
export const getMunicipalitiesByPrefecture = (prefectureName: string) => {
  const municipalityData = municipalities.find(m => m.prefecture === prefectureName)
  return municipalityData ? municipalityData.cities : defaultMunicipalities
}

// データベースから地域データを取得する関数（将来の拡張用）
export const getMunicipalitiesFromDatabase = async (prefectureName: string) => {
  // 現在は静的なデータを使用
  // 将来的にはSupabaseから動的に取得するように拡張可能
  return getMunicipalitiesByPrefecture(prefectureName)
}